<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Services\Enneagram\AuthorityV2\EnneagramPublicAuthorityV224RuntimeCloseout;
use App\Services\Enneagram\AuthorityV2\EnneagramPublicAuthorityV224RuntimeManifest;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Http;
use RuntimeException;
use Throwable;

final class PersonalityEnneagramAuthorityV2RuntimeCloseout extends Command
{
    /** @var resource|null */
    private $executeOutputHandle = null;

    private ?string $executeOutputPath = null;

    protected $signature = 'personality:enneagram-authority-v2-runtime-closeout
        {--artifacts-only : Generate review bootstrap artifacts from the frozen release report without runtime preflight}
        {--preflight : Build the no-write exact-SHA authorization packet and operator artifacts}
        {--execute : Execute only a separately authorized exact-SHA packet}
        {--source=docs/seo/personality/enneagram-authority-v2/enneagram-public-authority-v2-release-gate-22/release-gate-report.json : Exact 116-page release report}
        {--review-register= : Private completed 116-row human-review register}
        {--pre-readback= : Exact successful all-target pre-readback artifact}
        {--backend-deployed-sha= : Exact deployed backend Git SHA}
        {--frontend-deployed-sha= : Exact deployed frontend Git SHA}
        {--frontend-revision-url= : Read-only frontend revision endpoint}
        {--authorization-packet= : Exact packet generated by --preflight; required for execute}
        {--confirm-authorization-packet-sha256= : Canonical authorization packet SHA-256}
        {--operator-approved= : Separate exact dynamic production authorization phrase}
        {--rollback-token-output= : Absolute path outside Git for the signed rollback token}
        {--bound-by-admin-user-id= : Optional internal admin actor id}
        {--api-base-url= : Exact public backend API origin; required for preflight and execute}
        {--frontend-base-url= : Exact public frontend origin; required for preflight and execute}
        {--output-dir= : Preflight artifact directory}
        {--output= : Execute-mode redacted closeout artifact path}
        {--allow-testing : Permit execute only in APP_ENV=testing with SQLite}
        {--json : Emit redacted JSON}';

    protected $description = 'Generate review artifacts or run exact-SHA Enneagram Authority V2 runtime closeout controls.';

    public function handle(
        EnneagramPublicAuthorityV224RuntimeCloseout $closeout,
        EnneagramPublicAuthorityV224RuntimeManifest $manifest,
    ): int {
        try {
            $result = $this->runGuarded($closeout, $manifest);
        } catch (Throwable $throwable) {
            $result = $closeout->failureResult($throwable);
        }
        if (is_resource($this->executeOutputHandle)) {
            try {
                $result['closeout_output_persisted'] = true;
                $this->persistReservedExecuteOutput($result);
            } catch (Throwable $throwable) {
                $this->releaseExecuteOutputReservation(false);
                $result['ok'] = false;
                $result['status'] = ($result['writes_committed'] ?? false) === true
                    ? 'FAIL_CLOSED_PARTIAL_WRITES_COMMITTED'
                    : 'FAIL_CLOSED_NO_WRITES';
                $result['closeout_output_persisted'] = false;
                $result['error'] = 'Reserved closeout output persistence failed: '.$throwable->getMessage();
            }
        }
        $this->emit($result);

        return ($result['ok'] ?? false) === true ? self::SUCCESS : self::FAILURE;
    }

    /** @return array<string,mixed> */
    private function runGuarded(
        EnneagramPublicAuthorityV224RuntimeCloseout $closeout,
        EnneagramPublicAuthorityV224RuntimeManifest $manifest,
    ): array {
        $artifactsOnly = (bool) $this->option('artifacts-only');
        $preflight = (bool) $this->option('preflight');
        $execute = (bool) $this->option('execute');
        if ((int) $artifactsOnly + (int) $preflight + (int) $execute !== 1) {
            throw new RuntimeException('Exactly one of --artifacts-only, --preflight, or --execute is required.');
        }
        [$releaseReport, $releaseReportSha] = $this->jsonFileWithSha((string) $this->option('source'), 'release report');

        if ($artifactsOnly) {
            $artifacts = $manifest->artifacts($releaseReport);
            $generatedFiles = $this->writeReviewBootstrapArtifacts($artifacts);

            return [
                'schema_version' => 'enneagram_public_authority_v2_review_artifacts_generation.v1',
                'artifact' => EnneagramPublicAuthorityV224RuntimeCloseout::ARTIFACT,
                'ok' => true,
                'status' => 'PASS_REVIEW_ARTIFACTS_ONLY_GENERATED',
                'target_count' => EnneagramPublicAuthorityV224RuntimeManifest::TARGET_COUNT,
                'package_sha256' => (string) $releaseReport['package_sha256'],
                'release_report_sha256' => $releaseReportSha,
                'generated_file_count' => count($generatedFiles),
                'generated_files' => $generatedFiles,
                'private_review_register_completed' => false,
                'authorization_packet_generated' => false,
                'database_write_count' => 0,
                'http_request_count' => 0,
                'writes_committed' => false,
                'production_execution' => false,
            ];
        }

        [$reviewRegister, $reviewRegisterSha] = $this->jsonFileWithSha($this->requiredOption('review-register'), 'private review register');
        [$preReadback, $preReadbackSha] = $this->optionalJsonFileWithSha((string) $this->option('pre-readback'), 'pre-readback');
        $backendSha = $this->requiredOption('backend-deployed-sha');
        $frontendSha = $this->requiredOption('frontend-deployed-sha');
        $testingOverride = app()->environment('testing') && (bool) $this->option('allow-testing');
        $apiBaseUrl = $manifest->publicRuntimeOrigin(
            $this->requiredHttpsOrigin('api-base-url'),
            '--api-base-url',
            $testingOverride ? null : (string) config('app.url', ''),
        );
        $frontendBaseUrl = $manifest->publicRuntimeOrigin(
            $this->requiredHttpsOrigin('frontend-base-url'),
            '--frontend-base-url',
            $testingOverride ? null : (string) config('app.frontend_url', ''),
        );
        if ($preReadback === null && ! $testingOverride) {
            throw new RuntimeException('--pre-readback is required for production preflight and execute.');
        }
        $this->assertDeployedRevisions($backendSha, $frontendSha, $frontendBaseUrl);
        $revalidationEndpoint = $this->revalidationEndpoint();

        if ($preflight) {
            $result = $closeout->preflight(
                $releaseReport,
                $releaseReportSha,
                $reviewRegister,
                $reviewRegisterSha,
                $backendSha,
                $frontendSha,
                $apiBaseUrl,
                $frontendBaseUrl,
                $revalidationEndpoint,
                $preReadback,
                $preReadbackSha,
            );
            $this->writePreflightArtifacts($result);

            return $this->publicPreflightResult($result);
        }

        $this->assertWriteEnvironment();
        $this->reserveExecuteOutput($this->requiredOption('output'));
        [$packet] = $this->jsonFileWithSha($this->requiredOption('authorization-packet'), 'authorization packet');
        $result = $closeout->execute(
            $releaseReport,
            $releaseReportSha,
            $reviewRegister,
            $reviewRegisterSha,
            $backendSha,
            $frontendSha,
            $packet,
            $this->requiredOption('confirm-authorization-packet-sha256'),
            $this->requiredOption('operator-approved'),
            $this->requiredOption('rollback-token-output'),
            $apiBaseUrl,
            $frontendBaseUrl,
            $revalidationEndpoint,
            $this->revalidationSecret(),
            $this->optionalPositiveIntegerOption('bound-by-admin-user-id'),
            $preReadback,
            $preReadbackSha,
        );

        return $result;
    }

    private function assertDeployedRevisions(string $backendSha, string $frontendSha, string $frontendBaseUrl): void
    {
        foreach ([$backendSha, $frontendSha] as $sha) {
            if (preg_match('/^[0-9a-f]{40}$/', $sha) !== 1) {
                throw new RuntimeException('Backend/frontend deployed SHAs must be exact lowercase 40-character Git SHAs.');
            }
        }
        $revisionUrl = trim((string) $this->option('frontend-revision-url'));
        if ($revisionUrl !== '') {
            $this->assertUrlUsesOrigin($revisionUrl, $frontendBaseUrl, 'frontend-revision-url');
        }
        if (app()->environment('testing') && (bool) $this->option('allow-testing')) {
            return;
        }
        $revisionPath = base_path('../REVISION');
        if (! File::isFile($revisionPath) || trim(File::get($revisionPath)) !== $backendSha) {
            throw new RuntimeException('Deployed backend REVISION does not match the exact authorization SHA.');
        }
        $url = $this->requiredOption('frontend-revision-url');
        $this->assertUrlUsesOrigin($url, $frontendBaseUrl, 'frontend-revision-url');
        $response = Http::acceptJson()->withoutRedirecting()->timeout(15)->get($url);
        $observed = trim((string) ($response->json('revision') ?? $response->header('X-Revision') ?? $response->body()));
        if (! $response->successful() || $observed !== $frontendSha) {
            throw new RuntimeException('Deployed frontend revision endpoint does not match the exact authorization SHA.');
        }
    }

    private function assertWriteEnvironment(): void
    {
        if (app()->environment('production')) {
            return;
        }
        if ((bool) $this->option('allow-testing') && app()->environment('testing') && config('database.default') === 'sqlite') {
            return;
        }

        throw new RuntimeException('Execute mode requires APP_ENV=production, or --allow-testing with APP_ENV=testing and SQLite.');
    }

    /** @return array{array<string,mixed>,string} */
    private function jsonFileWithSha(string $path, string $label): array
    {
        $resolved = str_starts_with($path, DIRECTORY_SEPARATOR) ? $path : base_path($path);
        if (! File::isFile($resolved)) {
            throw new RuntimeException('Enneagram runtime '.$label.' not found.');
        }
        $raw = File::get($resolved);
        $decoded = json_decode($raw, true, 512, JSON_THROW_ON_ERROR);
        if (! is_array($decoded)) {
            throw new RuntimeException('Enneagram runtime '.$label.' must be a JSON object.');
        }

        return [$decoded, hash('sha256', $raw)];
    }

    /** @return array{array<string,mixed>|null,string|null} */
    private function optionalJsonFileWithSha(string $path, string $label): array
    {
        return trim($path) === '' ? [null, null] : $this->jsonFileWithSha($path, $label);
    }

    /** @param array<string,mixed> $result */
    private function writePreflightArtifacts(array $result): void
    {
        $directory = $this->requiredOption('output-dir');
        $resolved = str_starts_with($directory, DIRECTORY_SEPARATOR) ? $directory : base_path($directory);
        File::ensureDirectoryExists($resolved);
        $artifacts = $result['artifacts'];
        $files = [
            'human-review-checklist.json' => $artifacts['checklist'],
            'private-review-register-template.json' => $artifacts['review_register_template'],
            'readback-batches.json' => $artifacts['readback_batches'],
            'exact-sha-production-authorization-packet.json' => $result['authorization_packet'],
            'pr23-redacted-retrospective-template.json' => $artifacts['retrospective_template'],
            'runtime-preflight-summary.json' => $this->publicPreflightResult($result),
        ];
        foreach ($files as $name => $value) {
            File::put($resolved.DIRECTORY_SEPARATOR.$name, $this->encode($value)."\n");
        }
    }

    /** @param array<string,mixed> $artifacts @return list<string> */
    private function writeReviewBootstrapArtifacts(array $artifacts): array
    {
        $directory = $this->requiredOption('output-dir');
        $resolved = str_starts_with($directory, DIRECTORY_SEPARATOR) ? $directory : base_path($directory);
        File::ensureDirectoryExists($resolved);
        $files = [
            'human-review-checklist.json' => $artifacts['checklist'],
            'private-review-register-input.json' => $artifacts['review_register_template'],
            'readback-batches.json' => $artifacts['readback_batches'],
            'pr23-redacted-retrospective-template.json' => $artifacts['retrospective_template'],
        ];
        foreach (array_keys($files) as $name) {
            if (File::exists($resolved.DIRECTORY_SEPARATOR.$name)) {
                throw new RuntimeException('Review artifact already exists; refusing to overwrite it: '.$name.'.');
            }
        }

        $created = [];
        try {
            foreach ($files as $name => $value) {
                $path = $resolved.DIRECTORY_SEPARATOR.$name;
                $this->writeExclusiveArtifact($path, $this->encode($value)."\n");
                $created[] = $path;
            }
        } catch (Throwable $throwable) {
            File::delete($created);

            throw $throwable;
        }

        return array_keys($files);
    }

    private function writeExclusiveArtifact(string $path, string $payload): void
    {
        $handle = @fopen($path, 'x+b');
        if (! is_resource($handle)) {
            throw new RuntimeException('Unable to reserve review artifact output: '.basename($path).'.');
        }
        try {
            if (! @chmod($path, 0600)) {
                throw new RuntimeException('Unable to protect review artifact output: '.basename($path).'.');
            }
            $written = 0;
            while ($written < strlen($payload)) {
                $chunk = fwrite($handle, substr($payload, $written));
                if (! is_int($chunk) || $chunk < 1) {
                    throw new RuntimeException('Unable to persist review artifact output: '.basename($path).'.');
                }
                $written += $chunk;
            }
            if (! fflush($handle) || (function_exists('fsync') && ! fsync($handle))) {
                throw new RuntimeException('Unable to durably persist review artifact output: '.basename($path).'.');
            }
        } catch (Throwable $throwable) {
            fclose($handle);
            File::delete($path);

            throw $throwable;
        }
        fclose($handle);
    }

    private function reserveExecuteOutput(string $path): void
    {
        $resolved = str_starts_with($path, DIRECTORY_SEPARATOR) ? $path : base_path($path);
        File::ensureDirectoryExists(dirname($resolved));
        if (File::exists($resolved)) {
            throw new RuntimeException('Runtime closeout output already exists; refusing to overwrite it.');
        }
        $handle = @fopen($resolved, 'x+b');
        if (! is_resource($handle)) {
            throw new RuntimeException('Unable to reserve runtime closeout output before execution.');
        }
        $this->executeOutputHandle = $handle;
        $this->executeOutputPath = $resolved;
        if (! @chmod($resolved, 0600)) {
            $this->releaseExecuteOutputReservation(false);
            throw new RuntimeException('Unable to protect reserved runtime closeout output.');
        }
        $placeholder = [
            'schema_version' => 'enneagram_public_authority_v2_runtime_closeout.v1',
            'artifact' => EnneagramPublicAuthorityV224RuntimeCloseout::ARTIFACT,
            'ok' => false,
            'status' => 'EXECUTION_RESERVED_NOT_STARTED',
            'writes_committed' => false,
            'automatic_rollback' => false,
        ];
        $this->writeReservedExecuteOutput($this->encode($placeholder)."\n");
    }

    /** @param array<string,mixed> $result */
    private function persistReservedExecuteOutput(array $result): void
    {
        $this->writeReservedExecuteOutput($this->encode($result)."\n");
        $this->releaseExecuteOutputReservation(true);
    }

    private function writeReservedExecuteOutput(string $payload): void
    {
        if (! is_resource($this->executeOutputHandle) || $this->executeOutputPath === null
            || ! rewind($this->executeOutputHandle) || ! ftruncate($this->executeOutputHandle, 0)) {
            throw new RuntimeException('Runtime closeout output reservation is unavailable.');
        }
        $written = 0;
        while ($written < strlen($payload)) {
            $chunk = fwrite($this->executeOutputHandle, substr($payload, $written));
            if (! is_int($chunk) || $chunk < 1) {
                throw new RuntimeException('Unable to persist reserved runtime closeout output.');
            }
            $written += $chunk;
        }
        if (! fflush($this->executeOutputHandle)
            || (function_exists('fsync') && ! fsync($this->executeOutputHandle))) {
            throw new RuntimeException('Unable to durably persist reserved runtime closeout output.');
        }
    }

    private function releaseExecuteOutputReservation(bool $keepFile): void
    {
        if (is_resource($this->executeOutputHandle)) {
            fclose($this->executeOutputHandle);
        }
        if (! $keepFile && $this->executeOutputPath !== null) {
            File::delete($this->executeOutputPath);
        }
        $this->executeOutputHandle = null;
        $this->executeOutputPath = null;
    }

    /** @param array<string,mixed> $result @return array<string,mixed> */
    private function publicPreflightResult(array $result): array
    {
        $safe = $result;
        unset($safe['artifacts'], $safe['authorization_packet']['authorization_phrase']);

        return $safe;
    }

    private function revalidationEndpoint(): string
    {
        $value = trim((string) config('ops.content_release_observability.hmac_revalidation_url', ''));
        if ($value === '') {
            throw new RuntimeException('Frontend HMAC revalidation endpoint is not configured.');
        }

        return $value;
    }

    private function revalidationSecret(): string
    {
        $value = (string) config('ops.content_release_observability.hmac_revalidation_secret', '');
        if ($value === '') {
            throw new RuntimeException('Frontend HMAC revalidation secret is not configured.');
        }

        return $value;
    }

    private function requiredOption(string $name): string
    {
        $value = trim((string) $this->option($name));
        if ($value === '') {
            throw new RuntimeException('--'.$name.' is required.');
        }

        return $value;
    }

    private function requiredHttpsOrigin(string $name): string
    {
        $value = $this->requiredOption($name);
        $parts = parse_url($value);
        if (! filter_var($value, FILTER_VALIDATE_URL)
            || ! is_array($parts)
            || strtolower((string) ($parts['scheme'] ?? '')) !== 'https'
            || trim((string) ($parts['host'] ?? '')) === ''
            || isset($parts['user'])
            || isset($parts['pass'])
            || ! in_array((string) ($parts['path'] ?? ''), ['', '/'], true)
            || str_contains($value, '?')
            || str_contains($value, '#')) {
            throw new RuntimeException('--'.$name.' must be an exact HTTPS origin without credentials, path, query, or fragment.');
        }

        return rtrim($value, '/');
    }

    private function assertUrlUsesOrigin(string $url, string $expectedOrigin, string $name): void
    {
        $parts = parse_url($url);
        if (! filter_var($url, FILTER_VALIDATE_URL)
            || ! is_array($parts)
            || strtolower((string) ($parts['scheme'] ?? '')) !== 'https'
            || trim((string) ($parts['host'] ?? '')) === ''
            || isset($parts['user'])
            || isset($parts['pass'])
            || array_key_exists('query', $parts)
            || array_key_exists('fragment', $parts)) {
            throw new RuntimeException('--'.$name.' must be an exact HTTPS URL without credentials, query, or fragment.');
        }
        if (! hash_equals($this->canonicalHttpsOrigin($expectedOrigin), $this->canonicalHttpsOrigin($url))) {
            throw new RuntimeException('--'.$name.' must use the exact --frontend-base-url origin.');
        }
    }

    private function canonicalHttpsOrigin(string $url): string
    {
        $parts = parse_url($url);
        if (! is_array($parts)
            || strtolower((string) ($parts['scheme'] ?? '')) !== 'https'
            || trim((string) ($parts['host'] ?? '')) === '') {
            throw new RuntimeException('HTTPS origin is invalid.');
        }
        $host = strtolower((string) $parts['host']);
        $port = isset($parts['port']) ? (int) $parts['port'] : null;

        return 'https://'.$host.($port !== null && $port !== 443 ? ':'.$port : '');
    }

    private function optionalPositiveIntegerOption(string $name): ?int
    {
        $value = trim((string) $this->option($name));
        if ($value === '') {
            return null;
        }
        if (preg_match('/^[1-9][0-9]*$/D', $value) !== 1) {
            throw new RuntimeException('--'.$name.' must be a strict positive integer.');
        }
        $parsed = filter_var($value, FILTER_VALIDATE_INT, ['options' => ['min_range' => 1]]);
        if (! is_int($parsed)) {
            throw new RuntimeException('--'.$name.' must be within the supported integer range.');
        }

        return $parsed;
    }

    /** @param array<string,mixed> $result */
    private function emit(array $result): void
    {
        if ((bool) $this->option('json')) {
            $this->line($this->encode($result));

            return;
        }
        foreach (['ok', 'status', 'target_count', 'package_sha256', 'runtime_preflight_fingerprint', 'authorization_packet_sha256', 'rollback_token_sha256', 'writes_committed'] as $field) {
            if (array_key_exists($field, $result)) {
                $this->line($field.'='.(is_bool($result[$field]) ? ($result[$field] ? '1' : '0') : (string) $result[$field]));
            }
        }
        if (isset($result['error'])) {
            $this->line('error='.(string) $result['error']);
        }
    }

    private function encode(mixed $value): string
    {
        return (string) json_encode($value, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
    }
}
