version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"
    versioning-strategy: increase
    ignore:
      - dependency-name: "laravel/pail"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
      - dependency-name: "laravel/pint"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
      - dependency-name: "nunomaduro/collision"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
