<?php

return [
    // Admin API token
    'admin_token' => env('FAP_ADMIN_TOKEN', ''),

    // Content packages
    'content_package_version' => env('FAP_CONTENT_PACKAGE_VERSION', 'MBTI-CN-v0.3'),
    'content_packages_dir' => env('FAP_CONTENT_PACKAGES_DIR', null),
    'support_email' => env('FAP_SUPPORT_EMAIL', env('SUPPORT_EMAIL', '')),

    // Profile / scoring
    'profile_version' => env('FAP_PROFILE_VERSION', 'mbti32-v2.5'),
    'legacy_org_id' => (int) env('FAP_LEGACY_ORG_ID', 1),

    // Unified runtime feature gates
    'features' => [
        'agent' => (bool) env('FAP_FEATURE_AGENT', false),
        'insights' => (bool) env('FAP_FEATURE_INSIGHTS', false),
        'analytics' => (bool) env('FAP_FEATURE_ANALYTICS', true),
        'clinical_consent_enforce' => (bool) env('FAP_FEATURE_CLINICAL_CONSENT_ENFORCE', false),
    ],

    'payments' => [
        'enabled' => (bool) env('FAP_PAYMENTS_ENABLED', true),
        'webhooks_enabled' => (bool) env('FAP_PAYMENTS_WEBHOOKS_ENABLED', true),
    ],

    'content' => [
        'forbid_missing_reads' => (bool) env('FAP_FORBID_MISSING_READS', false),
        'forbid_missing_overrides' => (bool) env('FAP_FORBID_MISSING_OVERRIDES', false),
    ],

    'schema_baseline' => [
        'required_tables' => [
            'admin_users',
            'agent_decisions',
            'agent_feedback',
            'agent_messages',
            'agent_triggers',
            'ai_insight_feedback',
            'ai_insights',
            'attempt_quality',
            'attempts',
            'audit_logs',
            'content_pack_releases',
            'data_lifecycle_requests',
            'email_outbox',
            'embeddings',
            'events',
            'experiment_assignments',
            'failed_jobs',
            'feature_flags',
            'health_samples',
            'idempotency_keys',
            'identities',
            'ingest_batches',
            'integration_user_bindings',
            'integrations',
            'jobs',
            'lookup_events',
            'memories',
            'migration_backfills',
            'migration_index_audits',
            'migrations',
            'ops_healthz_snapshots',
            'orders',
            'organization_members',
            'payment_events',
            'permission_role',
            'permissions',
            'queue_dlq_replays',
            'report_jobs',
            'report_snapshots',
            'results',
            'role_user',
            'roles',
            'scale_norms_versions',
            'scales_registry',
            'screen_time_samples',
            'skus',
            'sleep_samples',
            'shares',
            'user_agent_settings',
            'users',
        ],
        'required_columns' => [
            'attempts' => [
                'answers_hash',
                'answers_json',
                'answers_summary_json',
                'answers_storage_path',
                'anon_id',
                'calculation_snapshot_json',
                'dir_version',
                'locale',
                'norm_version',
                'org_id',
                'pack_id',
                'result_json',
                'scoring_spec_version',
                'submitted_at',
                'type_code',
                'user_id',
            ],
            'email_outbox' => [
                'attempt_id',
                'consumed_at',
            ],
            'events' => [
                'experiments_json',
            ],
            'idempotency_keys' => [
                'external_id',
                'hash',
                'provider',
                'recorded_at',
            ],
            'ingest_batches' => [
                'actor_user_id',
                'auth_mode',
                'signature_ok',
                'source_ip',
            ],
            'integrations' => [
                'updated_at',
                'webhook_last_event_id',
                'webhook_last_received_at',
                'webhook_last_timestamp',
            ],
            'migration_backfills' => [
                'last_cursor',
            ],
            'orders' => [
                'org_id',
            ],
            'organization_members' => [
                'id',
                'role',
            ],
            'payment_events' => [
                'provider',
            ],
            'report_snapshots' => [
                'last_error',
                'org_id',
                'status',
                'updated_at',
            ],
            'results' => [
                'axis_states',
                'content_package_version',
                'org_id',
                'profile_version',
                'scoring_spec_version',
                'scores_pct',
            ],
            'skus' => [
                'org_id',
            ],
            'users' => [
                'created_at',
                'email',
                'email_verified_at',
                'name',
                'password',
                'phone_e164',
                'phone_verified_at',
                'updated_at',
            ],
        ],
        'feature_tables' => [
            'agent_decisions' => 'agent',
            'agent_feedback' => 'agent',
            'agent_messages' => 'agent',
            'agent_triggers' => 'agent',
            'user_agent_settings' => 'agent',
            'ai_insight_feedback' => 'insights',
            'ai_insights' => 'insights',
            'memories' => 'insights',
            'events' => 'analytics',
            'experiment_assignments' => 'analytics',
            'health_samples' => 'analytics',
            'ingest_batches' => 'analytics',
            'screen_time_samples' => 'analytics',
            'sleep_samples' => 'analytics',
        ],
    ],

    // Assessment driver registry (scales_registry.assessment_driver)
    'assessment_drivers' => [
        'mbti' => App\Services\Assessment\Drivers\MbtiDriver::class,
        'simple_score' => App\Services\Assessment\Drivers\SimpleScoreDriver::class,
        'simple_score_demo' => App\Services\Assessment\Drivers\SimpleScoreDriver::class,
        'demo_answers' => App\Services\Assessment\Drivers\SimpleScoreDriver::class,
        'generic_likert' => App\Services\Assessment\Drivers\GenericLikertDriver::class,
        'likert' => App\Services\Assessment\Drivers\GenericLikertDriver::class,
        'iq_test' => App\Services\Assessment\Drivers\IqTestDriver::class,
        'iq_raven' => App\Services\Assessment\Drivers\IqTestDriver::class,
        'iq' => App\Services\Assessment\Drivers\IqTestDriver::class,
        'generic_scoring' => App\Services\Assessment\Drivers\GenericScoringDriver::class,
        'big5' => App\Services\Assessment\Drivers\GenericScoringDriver::class,
        'big5_ocean' => App\Services\Assessment\Drivers\BigFiveOceanDriver::class,
        'clinical_combo_68' => App\Services\Assessment\Drivers\ClinicalCombo68Driver::class,
    ],

    // Persist raw answers (audit)
    'store_answers_to_storage' => (bool) env('FAP_STORE_ANSWERS_TO_STORAGE', false),

    // Reads debug
    'reads_debug' => (bool) env('FAP_READS_DEBUG', false),

    // RuleEngine switches
    're_debug' => (bool) env('FAP_RE_DEBUG', false),
    're_explain' => (bool) env('RE_EXPLAIN', false),
    're_ctx_tags' => (bool) env('RE_CTX_TAGS', false),
    're_tags' => (bool) env('RE_TAGS', false),

    're_tags_debug_n' => (int) env('RE_TAGS_DEBUG_N', 0),

    'rate_limits' => [
        'api_public_per_minute' => (int) env('FAP_RATE_LIMIT_PUBLIC_PER_MINUTE', 120),
        'api_auth_per_minute' => (int) env('FAP_RATE_LIMIT_AUTH_PER_MINUTE', 30),
        'api_attempt_submit_per_minute' => (int) env('FAP_RATE_LIMIT_ATTEMPT_SUBMIT_PER_MINUTE', 20),
        'api_webhook_per_minute' => (int) env('FAP_RATE_LIMIT_WEBHOOK_PER_MINUTE', 60),
        'bypass_in_test_env' => (bool) env('FAP_RATE_LIMIT_BYPASS_IN_TEST_ENV', true),
    ],

    'events' => [
        'max_top_keys' => (int) env('FAP_EVENTS_MAX_TOP_KEYS', 200),
        'max_depth' => (int) env('FAP_EVENTS_MAX_DEPTH', 4),
        'max_list_length' => (int) env('FAP_EVENTS_MAX_LIST_LENGTH', 50),
        'max_string_length' => (int) env('FAP_EVENTS_MAX_STRING_LENGTH', 2048),
        'max_payload_bytes' => (int) env('FAP_EVENTS_MAX_PAYLOAD_BYTES', 131072),
        'ingest_token' => env('EVENT_INGEST_TOKEN', ''),
    ],

    // Runtime overrides for business code via App\Support\RuntimeConfig
    'runtime' => [
        'AI_FAIL_OPEN_WHEN_REDIS_DOWN' => env('AI_FAIL_OPEN_WHEN_REDIS_DOWN', null),
        'FAP_CACHE_LOG' => env('FAP_CACHE_LOG', null),
        'FAP_FORBID_MISSING_HIGHLIGHTS' => env('FAP_FORBID_MISSING_HIGHLIGHTS', null),
        'FAP_FORBID_STORE_ASSET_SCAN' => env('FAP_FORBID_STORE_ASSET_SCAN', null),
        'FAP_FORBID_LEGACY_CTX_LOADER' => env('FAP_FORBID_LEGACY_CTX_LOADER', null),
        'LOOKUP_ORDER' => env('LOOKUP_ORDER', null),
        'APP_VERSION' => env('APP_VERSION', null),
        'REPORT_VERSION' => env('REPORT_VERSION', null),
        'IP_HASH_SALT' => env('IP_HASH_SALT', null),
        'NORMS_ENABLED' => env('NORMS_ENABLED', null),
        'NORMS_VERSION_PIN' => env('NORMS_VERSION_PIN', null),
        'RE_EXPLAIN_ITEMS_MAX' => env('RE_EXPLAIN_ITEMS_MAX', null),
        'RE_EXPLAIN' => env('RE_EXPLAIN', null),
        'RE_CTX_TAGS' => env('RE_CTX_TAGS', null),
        'RE_EXPLAIN_PAYLOAD' => env('RE_EXPLAIN_PAYLOAD', null),
        'FAP_OVR_DEBUG' => env('FAP_OVR_DEBUG', null),
        'FAP_OVR_TRACE' => env('FAP_OVR_TRACE', null),
        'PAYMENTS_ENABLED' => env('PAYMENTS_ENABLED', null),
        'WEBHOOK_ENABLED' => env('WEBHOOK_ENABLED', null),
        'PAYMENTS_DEV_MODE' => env('PAYMENTS_DEV_MODE', null),
        'CONTENT_GRAPH_ENABLED' => env('CONTENT_GRAPH_ENABLED', null),
        'CONTENT_GRAPH_PACK_PIN' => env('CONTENT_GRAPH_PACK_PIN', null),
        'FAP_DEBUG_FORCE_SHORT_SECTION' => env('FAP_DEBUG_FORCE_SHORT_SECTION', null),
        'FAP_FORBID_LEGACY_CARDS_LOADER' => env('FAP_FORBID_LEGACY_CARDS_LOADER', null),
        'FAP_CONTENT_PACKAGES_DIR' => env('FAP_CONTENT_PACKAGES_DIR', null),
        'FAP_OTP_DEV_CODE' => env('FAP_OTP_DEV_CODE', null),
        'FAP_FEATURE_FLAGS_VERSION' => env('FAP_FEATURE_FLAGS_VERSION', null),
        'FAP_FORBID_HIGHLIGHTS_FALLBACK' => env('FAP_FORBID_HIGHLIGHTS_FALLBACK', null),
        'RE_TAGS' => env('RE_TAGS', null),
        'RE_TAGS_DEBUG_N' => env('RE_TAGS_DEBUG_N', null),
        'RE_CONTEXT_KEYS' => env('RE_CONTEXT_KEYS', null),
        'OVR_EXPLAIN' => env('OVR_EXPLAIN', null),
        'WEEKLY_METRICS_ENABLED' => env('WEEKLY_METRICS_ENABLED', null),
        'EMAIL_OUTBOX_SEND' => env('EMAIL_OUTBOX_SEND', null),
        'FAP_ENV' => env('FAP_ENV', null),
        'FAP_BASE_URL' => env('FAP_BASE_URL', null),
        'SENTRY_RELEASE' => env('SENTRY_RELEASE', null),
        'REVISION' => env('REVISION', null),
        'GITHUB_ACTOR' => env('GITHUB_ACTOR', null),
        'USER' => env('USER', null),
        'MBTI_CONTENT_PACKAGE' => env('MBTI_CONTENT_PACKAGE', null),
        'CACHE_PREFIX' => env('CACHE_PREFIX', null),
        'FEEDBACK_ENABLED' => env('FEEDBACK_ENABLED', null),
    ],

    'selfcheck_known_assets' => [
        'manifest.json',
        'version.json',
        'questions.json',
        'scoring_spec.json',
        'quality_checks.json',
        'norms.json',
        'content_graph.json',
        'identity_layers.json',
        'interpretation_spec.json',
        'commercial_spec.json',
        'ai_spec.json',
        'telemetry_spec.json',
        'audit_spec.json',
        'report_borderline_notes.json',
        'report_borderline_templates.json',
        'report_cards_career.json',
        'report_cards_fallback_career.json',
        'report_cards_fallback_growth.json',
        'report_cards_fallback_relationships.json',
        'report_cards_fallback_stress_recovery.json',
        'report_cards_fallback_traits.json',
        'report_cards_growth.json',
        'report_cards_relationships.json',
        'report_cards_stress_recovery.json',
        'report_cards_traits.json',
        'report_highlights.json',
        'report_highlights_policy.json',
        'report_highlights_pools.json',
        'report_highlights_rules.json',
        'report_highlights_templates.json',
        'report_identity_cards.json',
        'report_overrides.json',
        'report_recommended_reads.json',
        'report_roles.json',
        'report_rules.json',
        'report_section_policies.json',
        'report_select_rules.json',
        'report_share_templates.json',
        'report_strategies.json',
        'type_profiles.json',
        'assets/',
        'meta/',
        'reads/',
        'role_cards/',
        'share_templates/',
        'strategy_cards/',
    ],
];
