<?php

declare(strict_types=1);

return [
    'enabled' => env('PUBLIC_CONTENT_RUNTIME_METRICS_ENABLED', true),
    'warm_production_enabled' => env('PUBLIC_CONTENT_WARM_PRODUCTION_ENABLED', false),
    'cache_store' => env('PUBLIC_CONTENT_RUNTIME_METRICS_STORE', 'redis'),
    'minute_retention_days' => 7,
    'daily_retention_days' => 90,
    'rollup_lag_minutes' => 2,
    'query_max_minutes' => 90 * 24 * 60,
    'allowed_locales' => ['en', 'zh-CN', 'unknown'],
    'duration_buckets_ms' => [25, 50, 100, 250, 500, 1000, 2000, 5000, 10000, 30000],

    'probe' => [
        'enabled' => env('PUBLIC_CONTENT_DELIVERY_PROBE_ENABLED', true),
        'base_url' => env('PUBLIC_CONTENT_DELIVERY_PROBE_BASE_URL', env('APP_URL', 'http://localhost')),
        'cache_store' => env('PUBLIC_CONTENT_DELIVERY_PROBE_STORE', env('PUBLIC_CONTENT_RUNTIME_METRICS_STORE', 'redis')),
        'connect_timeout_seconds' => 3,
        'timeout_seconds' => 8,
        'payload_budget_bytes' => 1048576,
        'retention_seconds' => 7 * 24 * 60 * 60,
        'targets' => [
            [
                'id' => 'l1_mbti_intj_a_en',
                'family' => 'mbti',
                'priority' => 'L1',
                'locale' => 'en',
                'path' => '/api/v0.5/personality/intj-a',
                'query' => ['locale' => 'en', 'org_id' => 0, 'scale_code' => 'MBTI'],
                'readback_profile' => 'mbti_detail',
                'allowed_cache_states' => ['unknown'],
                'required_content_authority' => 'personality.page.content.v1',
                'require_content_aggregate_sha256' => true,
            ],
            [
                'id' => 'l2_big_five_hub_en',
                'family' => 'big_five',
                'priority' => 'L2',
                'locale' => 'en',
                'path' => '/api/v0.5/personality-content-assets/big_five/hub/big-five',
                'query' => ['locale' => 'en', 'org_id' => 0],
                'readback_profile' => 'personality_asset_detail',
                'allowed_cache_states' => ['unknown'],
                'required_content_authority' => 'personality.page.content.v1',
                'require_content_aggregate_sha256' => true,
            ],
            [
                'id' => 'l3_career_industries_en',
                'family' => 'career_industries',
                'priority' => 'L3',
                'locale' => 'en',
                'path' => '/api/v0.5/career/industries',
                'query' => ['locale' => 'en', 'org_id' => 0],
                'readback_profile' => 'career_industries',
                'allowed_cache_states' => ['unknown'],
            ],
        ],
    ],

    // Exact parameterized route templates are the authority boundary. Never add
    // private attempt, report, order, payment, shortlist, or internal routes here.
    'routes' => [
        'api/v0.5/personality' => ['family' => 'mbti', 'priority' => 'L1'],
        'api/v0.5/personality/{type}' => ['family' => 'mbti', 'priority' => 'L1'],
        'api/v0.5/personality/{type}/seo' => ['family' => 'mbti', 'priority' => 'L1'],
        'api/v0.5/personality/comparisons' => ['family' => 'mbti', 'priority' => 'L1'],
        'api/v0.5/personality/comparisons/{comparison}' => ['family' => 'mbti', 'priority' => 'L1'],
        'api/v0.5/personality-content-assets' => ['family' => 'personality_assets', 'priority' => 'L2'],
        'api/v0.5/personality-content-assets/{framework}/{slug}' => ['framework_family' => true],
        'api/v0.5/personality-content-assets/{framework}/{entityType}/{code}' => ['framework_family' => true],
        'api/v0.5/articles' => ['family' => 'articles', 'priority' => 'L3'],
        'api/v0.5/articles/{slug}' => ['family' => 'articles', 'priority' => 'L3'],
        'api/v0.5/articles/{slug}/seo' => ['family' => 'articles', 'priority' => 'L3'],
        'api/v0.5/research' => ['family' => 'research', 'priority' => 'L3'],
        'api/v0.5/research/{slug}' => ['family' => 'research', 'priority' => 'L3'],
        'api/v0.5/support/articles' => ['family' => 'support', 'priority' => 'L3'],
        'api/v0.5/support/articles/{slug}' => ['family' => 'support', 'priority' => 'L3'],
        'api/v0.5/support/guides' => ['family' => 'support', 'priority' => 'L3'],
        'api/v0.5/support/guides/{slug}' => ['family' => 'support', 'priority' => 'L3'],
        'api/v0.5/support/interpretation-guides' => ['family' => 'support', 'priority' => 'L3'],
        'api/v0.5/support/interpretation-guides/{slug}' => ['family' => 'support', 'priority' => 'L3'],
        'api/v0.5/content-pages/{slug}' => ['family' => 'content_pages', 'priority' => 'L3'],
        'api/v0.5/landing-surfaces/{surfaceKey}' => ['family' => 'landing_surfaces', 'priority' => 'L3'],
        'api/v0.5/career-guides' => ['family' => 'career_guides', 'priority' => 'L3'],
        'api/v0.5/career-guides/{slug}' => ['family' => 'career_guides', 'priority' => 'L3'],
        'api/v0.5/career-guides/{slug}/seo' => ['family' => 'career_guides', 'priority' => 'L3'],
        'api/v0.5/career-jobs' => ['family' => 'career_jobs', 'priority' => 'L3'],
        'api/v0.5/career-jobs/{slug}' => ['family' => 'career_jobs', 'priority' => 'L3'],
        'api/v0.5/career-jobs/{slug}/seo' => ['family' => 'career_jobs', 'priority' => 'L3'],
        'api/v0.5/career/recommendations/mbti' => ['family' => 'career_recommendations', 'priority' => 'L3'],
        'api/v0.5/career/recommendations/mbti/{type}' => ['family' => 'career_recommendations', 'priority' => 'L3'],
        'api/v0.5/career/directory' => ['family' => 'career_directory', 'priority' => 'L3'],
        'api/v0.5/career/industries' => ['family' => 'career_industries', 'priority' => 'L3'],
        'api/v0.5/career/jobs' => ['family' => 'career_jobs', 'priority' => 'L3'],
        'api/v0.5/career/jobs/{slug}' => ['family' => 'career_jobs', 'priority' => 'L3'],
        'api/v0.5/topics' => ['family' => 'topics', 'priority' => 'L3'],
        'api/v0.5/topics/{slug}' => ['family' => 'topics', 'priority' => 'L3'],
        'api/v0.5/topics/{slug}/seo' => ['family' => 'topics', 'priority' => 'L3'],
    ],

    'framework_families' => [
        'big-five' => ['family' => 'big_five', 'priority' => 'L2'],
        'big_five' => ['family' => 'big_five', 'priority' => 'L2'],
        'enneagram' => ['family' => 'enneagram', 'priority' => 'L3'],
    ],
];
