<?php

return [
    'enabled' => env('SEO_INTEL_ENABLED', false),
    'connection' => env('SEO_INTEL_DB_CONNECTION', 'seo_intel'),
    'write_enabled' => env('SEO_INTEL_WRITE_ENABLED', false),
    'collectors_enabled' => env('SEO_INTEL_COLLECTORS_ENABLED', false),
    'dry_run_default' => env('SEO_INTEL_DRY_RUN_DEFAULT', true),
    'allow_external_api_calls' => false,
    'allow_production_crawl' => false,
    'allow_production_log_read' => false,
    'allowed_collectors' => [
        'noop',
        'url_truth_inventory',
        'drift_foundation',
        'crawler_log_foundation',
        'attribution_revenue_foundation',
        'gsc_foundation',
        'baidu_foundation',
        'indexnow_foundation',
        'so360_foundation',
        'sogou_foundation',
        'shenma_foundation',
        'chinese_crawler_log_foundation',
        'issue_queue_foundation',
    ],
    'default_collector' => 'noop',
    'collector_timeout_seconds' => env('SEO_INTEL_COLLECTOR_TIMEOUT_SECONDS', 30),
    'url_truth_inventory' => [
        'canary_default_limit' => 10,
        'canary_max_limit' => 50,
        'write_requires_bound' => true,
        'source_authority' => 'backend_sitemap_source',
        'allowed_page_entity_types' => [
            'home',
            'test_hub',
            'test_detail',
            'article',
            'topic',
            'personality',
            'career_job',
            'career_recommendation',
            'methodology',
            'dataset',
            'report_preview',
            'landing_page',
        ],
        'forbidden_page_entity_types' => [
            'take',
            'result',
            'order',
            'share',
            'pay',
            'checkout',
            'report_private',
        ],
        'allowed_source_authorities' => [
            'backend_sitemap_source',
            'cms_article',
            'cms_topic',
            'cms_personality',
            'cms_career_job',
            'cms_career_recommendation',
            'scale_catalog',
            'backend_public_surface',
        ],
        'forbidden_source_authorities' => [
            'node2_local_laravel',
            'node2_local_db',
            'frontend_fallback',
            'static_llms_fallback',
            'static_sitemap_fallback',
            'ga4',
            'baidu_tongji',
            'synthetic_production_fixture',
        ],
        'sample_hash_limit' => 5,
        'backend_authority_canary_candidates' => [
            [
                'path' => '/en',
                'locale' => 'en',
                'page_entity_type' => 'home',
                'entity_id_or_slug' => 'home:en',
                'source_authority' => 'backend_public_surface',
            ],
            [
                'path' => '/zh',
                'locale' => 'zh-CN',
                'page_entity_type' => 'home',
                'entity_id_or_slug' => 'home:zh',
                'source_authority' => 'backend_public_surface',
            ],
            [
                'path' => '/en/tests',
                'locale' => 'en',
                'page_entity_type' => 'test_hub',
                'entity_id_or_slug' => 'test_hub:en',
                'source_authority' => 'backend_public_surface',
            ],
            [
                'path' => '/zh/tests',
                'locale' => 'zh-CN',
                'page_entity_type' => 'test_hub',
                'entity_id_or_slug' => 'test_hub:zh',
                'source_authority' => 'backend_public_surface',
            ],
            [
                'path' => '/en/tests/mbti-personality-test-16-personality-types',
                'locale' => 'en',
                'page_entity_type' => 'test_detail',
                'entity_id_or_slug' => 'mbti-personality-test-16-personality-types',
                'source_authority' => 'scale_catalog',
            ],
            [
                'path' => '/en/tests/big-five-personality-test-ocean-model',
                'locale' => 'en',
                'page_entity_type' => 'test_detail',
                'entity_id_or_slug' => 'big-five-personality-test-ocean-model',
                'source_authority' => 'scale_catalog',
            ],
            [
                'path' => '/en/tests/enneagram-personality-test-nine-types',
                'locale' => 'en',
                'page_entity_type' => 'test_detail',
                'entity_id_or_slug' => 'enneagram-personality-test-nine-types',
                'source_authority' => 'scale_catalog',
            ],
        ],
    ],
    'drift_foundation' => [
        'allow_single_url_dry_run' => true,
        'max_url_dry_run_count' => 1,
        'extract_fields' => [
            'canonical',
            'title',
            'description',
            'robots',
            'jsonld',
            'hreflang',
        ],
    ],
    'crawler_log_foundation' => [
        'supported_bot_families' => [
            'googlebot',
            'bingbot',
            'baiduspider',
            '360spider',
            'sogou',
            'shenma_yisou',
            'bytespider',
            'ai_crawler',
            'unknown_bot',
            'human_or_unknown',
        ],
    ],
    'attribution_revenue_foundation' => [
        'canonical_funnel_events' => [
            'start_attempt',
            'submit_attempt',
            'view_result',
            'click_unlock',
            'create_order',
            'payment_confirmed',
            'purchase_success',
        ],
        'source_engine_values' => [
            'google',
            'baidu',
            'bing_indexnow',
            'llms',
            'direct',
            'paid_google',
            'paid_baidu',
            'unknown',
        ],
        'consent_state_values' => [
            'granted',
            'denied',
            'unknown',
            'not_applicable',
        ],
        'traffic_quality_excluded_by_default' => [
            'qa',
            'internal',
            'bot',
        ],
        'purchase_truth_source' => 'backend_orders_payment_benefits',
        'ga4_purchase_truth' => false,
        'baidu_purchase_truth' => false,
        'keyword_purchase_attribution_allowed' => false,
    ],
    'gsc_enabled' => env('SEO_INTEL_GSC_ENABLED', false),
    'gsc_live_api_enabled' => false,
    'gsc_property_url' => env('SEO_INTEL_GSC_PROPERTY_URL', null),
    'gsc_backfill_lag_days' => 3,
    'gsc_default_window_days' => 28,
    'gsc_foundation' => [
        'source_engine' => 'google',
        'brand_query_terms' => [
            'fermat',
            'fermatmind',
            '费马',
            '费马测试',
            'fap',
        ],
        'query_purchase_attribution_allowed' => false,
        'purchase_truth_source' => 'backend_orders_payment_benefits',
    ],
    'baidu_enabled' => env('SEO_INTEL_BAIDU_ENABLED', false),
    'baidu_live_api_enabled' => false,
    'indexnow_enabled' => env('SEO_INTEL_INDEXNOW_ENABLED', false),
    'indexnow_live_api_enabled' => false,
    'baidu_source_engine' => 'baidu',
    'indexnow_source_engine' => 'bing_indexnow',
    'baidu_foundation' => [
        'source_engine' => 'baidu',
        'real_url_submission_allowed' => false,
        'draft_url_submission_allowed' => false,
        'search_channel_purchase_attribution_allowed' => false,
        'purchase_truth_source' => 'backend_orders_payment_benefits',
    ],
    'indexnow_foundation' => [
        'source_engine' => 'bing_indexnow',
        'real_url_submission_allowed' => false,
        'draft_url_submission_allowed' => false,
        'search_channel_purchase_attribution_allowed' => false,
        'purchase_truth_source' => 'backend_orders_payment_benefits',
    ],
    'so360_enabled' => env('SEO_INTEL_SO360_ENABLED', false),
    'so360_live_api_enabled' => false,
    'sogou_enabled' => env('SEO_INTEL_SOGOU_ENABLED', false),
    'sogou_live_api_enabled' => false,
    'shenma_enabled' => env('SEO_INTEL_SHENMA_ENABLED', false),
    'shenma_live_api_enabled' => false,
    'domestic_search_foundation' => [
        'allowed_engines' => [
            'so360',
            'sogou',
            'shenma',
        ],
        'real_url_submission_allowed' => false,
        'draft_url_submission_allowed' => false,
        'private_flow_submission_allowed' => false,
        'noindex_url_submission_allowed' => false,
        'engine_specific_page_generation_allowed' => false,
        'search_channel_purchase_attribution_allowed' => false,
        'purchase_truth_source' => 'backend_orders_payment_benefits',
    ],
    'so360_foundation' => [
        'engine' => 'so360',
        'source_engine' => 'so360',
    ],
    'sogou_foundation' => [
        'engine' => 'sogou',
        'source_engine' => 'sogou',
    ],
    'shenma_foundation' => [
        'engine' => 'shenma',
        'source_engine' => 'shenma',
    ],
    'allow_raw_ip_storage' => false,
    'allow_raw_user_agent_storage' => false,
    'allow_raw_cookie_storage' => false,
    'chinese_crawler_logs_enabled' => env('SEO_INTEL_CHINESE_CRAWLER_LOGS_ENABLED', false),
    'chinese_crawler_live_log_read_enabled' => false,
    'crawler_log_source' => env('SEO_INTEL_CRAWLER_LOG_SOURCE', null),
    'chinese_crawler_log_foundation' => [
        'source_engine_mapping' => [
            'googlebot' => 'google',
            'bingbot' => 'bing_indexnow',
            'baiduspider' => 'baidu',
            'so360_spider' => 'so360',
            'sogou_spider' => 'sogou',
            'shenma_yisou' => 'shenma',
            'bytespider' => 'ai_search',
            'ai_crawler' => 'ai_search',
            'unknown_bot' => 'unknown',
            'human_or_unknown' => 'unknown',
        ],
        'private_flow_warning_enabled' => true,
        'crawler_hit_grants_indexability' => false,
        'search_channel_purchase_attribution_allowed' => false,
    ],
    'issue_queue_enabled' => env('SEO_INTEL_ISSUE_QUEUE_ENABLED', false),
    'issue_summary_api_enabled' => env('SEO_INTEL_ISSUE_SUMMARY_API_ENABLED', false),
    'auto_publish_enabled' => false,
    'auto_cms_mutation_enabled' => false,
    'auto_pseo_enabled' => false,
    'issue_queue_foundation' => [
        'cms_summary_read_only' => true,
        'cms_mutation_allowed' => false,
        'auto_publish_allowed' => false,
        'auto_pseo_allowed' => false,
        'search_channel_purchase_attribution_allowed' => false,
        'metabase_data_source' => 'seo_intel_only',
    ],
    'allow_pii_detail' => false,
    'allow_raw_order_no' => false,
    'allow_raw_attempt_id' => false,
    'allow_raw_payment_payload' => false,
    'allow_raw_email' => false,
    'default_environment' => env('APP_ENV', 'production'),
];
