<?php

return [
    'enabled' => env('SEO_INTEL_ENABLED', false),
    'connection' => env('SEO_INTEL_DB_CONNECTION', 'seo_intel'),
    'write_enabled' => env('SEO_INTEL_WRITE_ENABLED', false),
    'collectors_enabled' => env('SEO_INTEL_COLLECTORS_ENABLED', false),
    'dry_run_default' => env('SEO_INTEL_DRY_RUN_DEFAULT', true),
    'allow_external_api_calls' => false,
    'allowed_collectors' => [
        'noop',
        'url_truth_inventory',
    ],
    'default_collector' => 'noop',
    'collector_timeout_seconds' => env('SEO_INTEL_COLLECTOR_TIMEOUT_SECONDS', 30),
    'url_truth_inventory' => [
        'allowed_page_entity_types' => [
            'home',
            'test_hub',
            'test_detail',
            'article',
            'topic',
            'personality',
            'career_job',
            'career_recommendation',
            'methodology',
            'dataset',
            'report_preview',
            'landing_page',
        ],
        'forbidden_page_entity_types' => [
            'take',
            'result',
            'order',
            'share',
            'pay',
            'checkout',
            'report_private',
        ],
        'allowed_source_authorities' => [
            'backend_sitemap_source',
            'cms_article',
            'cms_topic',
            'cms_personality',
            'cms_career_job',
            'cms_career_recommendation',
            'scale_catalog',
            'backend_public_surface',
        ],
        'forbidden_source_authorities' => [
            'node2_local_laravel',
            'frontend_fallback',
            'static_llms_fallback',
            'static_sitemap_fallback',
            'ga4',
            'baidu_tongji',
        ],
        'sample_hash_limit' => 5,
    ],
    'allow_pii_detail' => false,
    'allow_raw_order_no' => false,
    'allow_raw_attempt_id' => false,
    'allow_raw_payment_payload' => false,
    'allow_raw_email' => false,
    'default_environment' => env('APP_ENV', 'production'),
];
