<?php

return [
    'enabled' => env('SEO_INTEL_ENABLED', false),
    'connection' => env('SEO_INTEL_DB_CONNECTION', 'seo_intel'),
    'write_enabled' => env('SEO_INTEL_WRITE_ENABLED', false),
    'collectors_enabled' => env('SEO_INTEL_COLLECTORS_ENABLED', false),
    'dry_run_default' => env('SEO_INTEL_DRY_RUN_DEFAULT', true),
    'allow_external_api_calls' => false,
    'allow_production_crawl' => false,
    'allow_production_log_read' => false,
    'allowed_collectors' => [
        'noop',
        'url_truth_inventory',
        'drift_foundation',
        'crawler_log_foundation',
        'attribution_revenue_foundation',
        'gsc_foundation',
        'baidu_foundation',
        'indexnow_foundation',
    ],
    'default_collector' => 'noop',
    'collector_timeout_seconds' => env('SEO_INTEL_COLLECTOR_TIMEOUT_SECONDS', 30),
    'url_truth_inventory' => [
        'allowed_page_entity_types' => [
            'home',
            'test_hub',
            'test_detail',
            'article',
            'topic',
            'personality',
            'career_job',
            'career_recommendation',
            'methodology',
            'dataset',
            'report_preview',
            'landing_page',
        ],
        'forbidden_page_entity_types' => [
            'take',
            'result',
            'order',
            'share',
            'pay',
            'checkout',
            'report_private',
        ],
        'allowed_source_authorities' => [
            'backend_sitemap_source',
            'cms_article',
            'cms_topic',
            'cms_personality',
            'cms_career_job',
            'cms_career_recommendation',
            'scale_catalog',
            'backend_public_surface',
        ],
        'forbidden_source_authorities' => [
            'node2_local_laravel',
            'frontend_fallback',
            'static_llms_fallback',
            'static_sitemap_fallback',
            'ga4',
            'baidu_tongji',
        ],
        'sample_hash_limit' => 5,
    ],
    'drift_foundation' => [
        'allow_single_url_dry_run' => true,
        'max_url_dry_run_count' => 1,
        'extract_fields' => [
            'canonical',
            'title',
            'description',
            'robots',
            'jsonld',
            'hreflang',
        ],
    ],
    'crawler_log_foundation' => [
        'supported_bot_families' => [
            'googlebot',
            'bingbot',
            'baiduspider',
            '360spider',
            'sogou',
            'shenma_yisou',
            'bytespider',
            'ai_crawler',
            'unknown_bot',
            'human_or_unknown',
        ],
    ],
    'attribution_revenue_foundation' => [
        'canonical_funnel_events' => [
            'start_attempt',
            'submit_attempt',
            'view_result',
            'click_unlock',
            'create_order',
            'payment_confirmed',
            'purchase_success',
        ],
        'source_engine_values' => [
            'google',
            'baidu',
            'bing_indexnow',
            'llms',
            'direct',
            'paid_google',
            'paid_baidu',
            'unknown',
        ],
        'consent_state_values' => [
            'granted',
            'denied',
            'unknown',
            'not_applicable',
        ],
        'traffic_quality_excluded_by_default' => [
            'qa',
            'internal',
            'bot',
        ],
        'purchase_truth_source' => 'backend_orders_payment_benefits',
        'ga4_purchase_truth' => false,
        'baidu_purchase_truth' => false,
        'keyword_purchase_attribution_allowed' => false,
    ],
    'gsc_enabled' => env('SEO_INTEL_GSC_ENABLED', false),
    'gsc_live_api_enabled' => false,
    'gsc_property_url' => env('SEO_INTEL_GSC_PROPERTY_URL', null),
    'gsc_backfill_lag_days' => 3,
    'gsc_default_window_days' => 28,
    'gsc_foundation' => [
        'source_engine' => 'google',
        'brand_query_terms' => [
            'fermat',
            'fermatmind',
            '费马',
            '费马测试',
            'fap',
        ],
        'query_purchase_attribution_allowed' => false,
        'purchase_truth_source' => 'backend_orders_payment_benefits',
    ],
    'baidu_enabled' => env('SEO_INTEL_BAIDU_ENABLED', false),
    'baidu_live_api_enabled' => false,
    'indexnow_enabled' => env('SEO_INTEL_INDEXNOW_ENABLED', false),
    'indexnow_live_api_enabled' => false,
    'baidu_source_engine' => 'baidu',
    'indexnow_source_engine' => 'bing_indexnow',
    'baidu_foundation' => [
        'source_engine' => 'baidu',
        'real_url_submission_allowed' => false,
        'draft_url_submission_allowed' => false,
        'search_channel_purchase_attribution_allowed' => false,
        'purchase_truth_source' => 'backend_orders_payment_benefits',
    ],
    'indexnow_foundation' => [
        'source_engine' => 'bing_indexnow',
        'real_url_submission_allowed' => false,
        'draft_url_submission_allowed' => false,
        'search_channel_purchase_attribution_allowed' => false,
        'purchase_truth_source' => 'backend_orders_payment_benefits',
    ],
    'allow_pii_detail' => false,
    'allow_raw_order_no' => false,
    'allow_raw_attempt_id' => false,
    'allow_raw_payment_payload' => false,
    'allow_raw_email' => false,
    'default_environment' => env('APP_ENV', 'production'),
];
