<?php

declare(strict_types=1);

return [
    'manifest_schema_version' => 'storage_manifest.v1',
    'exact_manifest_schema_version' => 'storage_exact_manifest.v1',
    'snapshot_schema_version' => 'storage_snapshot.v1',
    'blob_offload_plan_schema_version' => 'storage_blob_offload_plan.v1',
    'rehydrate_plan_schema_version' => 'storage_rehydrate_exact_release_plan.v1',
    'quarantine_plan_schema_version' => 'storage_quarantine_exact_roots_plan.v1',
    'quarantine_run_schema_version' => 'storage_quarantine_exact_root_run.v1',
    'quarantine_root_dir' => 'app/private/quarantine/release_roots',
    'restore_plan_schema_version' => 'storage_restore_quarantined_root_plan.v1',
    'restore_run_schema_version' => 'storage_restore_quarantined_root_run.v1',
    'restore_root_dir' => 'app/private/quarantine/restore_runs',
    'purge_plan_schema_version' => 'storage_purge_quarantined_root_plan.v1',
    'purge_run_schema_version' => 'storage_purge_quarantined_root_run.v1',
    'purge_root_dir' => 'app/private/quarantine/purge_runs',
    'retirement_plan_schema_version' => 'storage_retire_exact_roots_plan.v1',
    'retirement_run_schema_version' => 'storage_retire_exact_roots_run.v1',
    'retirement_root_dir' => 'app/private/retirement_runs',
    'blob_catalog_enabled' => false,
    'manifest_catalog_enabled' => false,
    'snapshot_catalog_enabled' => false,
    'artifact_dual_write_enabled' => false,
    'receipt_ledger_dual_write_enabled' => false,
    'artifact_slot_version_dual_write_enabled' => false,
    'lifecycle_ledger_dual_write_enabled' => false,
    'access_projection_dual_write_enabled' => false,
    'content_pack_v2_dual_write_enabled' => false,
    'resolver_materialization_enabled' => false,
    'packs_v2_remote_rehydrate_enabled' => false,
    'blob_offload_disk' => env('STORAGE_BLOB_OFFLOAD_DISK', 's3'),
    'blob_offload_prefix' => env('STORAGE_BLOB_OFFLOAD_PREFIX', 'rollout/blobs'),
    'blob_offload_storage_class' => env('STORAGE_BLOB_OFFLOAD_STORAGE_CLASS'),
];
