services:
  grafana:
    image: grafana/grafana:11.0.0
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_MYSQL_HOST: ${GF_MYSQL_HOST}
      GF_MYSQL_PORT: ${GF_MYSQL_PORT}
      GF_MYSQL_DB: ${GF_MYSQL_DB}
      GF_MYSQL_USER: ${GF_MYSQL_USER}
      GF_MYSQL_PASSWORD: ${GF_MYSQL_PASSWORD}
    volumes:
      - ../grafana/provisioning:/etc/grafana/provisioning
      - ../grafana/dashboards:/var/lib/grafana/dashboards

  metabase:
    image: metabase/metabase:v0.49.12
    ports:
      - "3001:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase-data:/metabase-data

  mysql:
    profiles: ["phase-d-deps"]
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fap_obs
    ports:
      - "13306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    profiles: ["phase-d-deps"]
    image: redis:6-alpine
    ports:
      - "16379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10

volumes:
  metabase-data:
