services:
  grafana:
    image: grafana/grafana:11.0.0
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_MYSQL_HOST: ${GF_MYSQL_HOST}
      GF_MYSQL_PORT: ${GF_MYSQL_PORT}
      GF_MYSQL_DB: ${GF_MYSQL_DB}
      GF_MYSQL_USER: ${GF_MYSQL_USER}
      GF_MYSQL_PASSWORD: ${GF_MYSQL_PASSWORD}
    volumes:
      - ../grafana/provisioning:/etc/grafana/provisioning
      - ../grafana/dashboards:/var/lib/grafana/dashboards

  metabase:
    image: metabase/metabase:v0.49.12
    ports:
      - "3001:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase-data:/metabase-data

volumes:
  metabase-data:
